market_manage_system/models/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   __init__.py.py

@Time    :   2020/12/31 13:19

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from .base import db
def init_app(app):
	db.init_app(app)

market_manage_system/models/auth_info.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   auth_info.py

@Time    :   2020/12/31 14:26

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''
from werkzeug.security import generate_password_hash
from .base import db
from .staff_info import  Staff
# 可能的原因是 view 里目前只用了Account model 所以只识别该文件，因此需要把其他的model文件导入
# from .good_info import Goods
# from .supplier_info import Supplier
# from .member_info import Member
# from .entry_info import Entry
# from .factory_info import Factory
from .sale_info import Sale
# from .stock_info import Stock
from .trade_info import Trade
class Account(db.Model):
	ID=db.Column(db.INTEGER,primary_key=True)
	username=db.Column(db.String(255))
	password=db.Column(db.String(255))
	authority=db.Column(db.SMALLINT)  # 0 收银员 1 管理员
	staff_ID=db.Column(db.String(255),db.ForeignKey('staff.ID'))
	staff=db.relationship('Staff',backref='account')
	def __init__(self,username,password):
		self.username=username
		self.password=generate_password_hash(password)
		self.authority=0 #默认为零
	def __repr__(self):
		return '<username %r>' % self.username
	def todict(self):
		return {
			'ID':self.ID,
			'username':self.username,
			'password':self.password,
			'authority':self.authority,
			'staff_ID':self.staff_ID
		}

market_manage_system/models/base.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   base.py

@Time    :   2020/12/31 14:06

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from flask_sqlalchemy import SQLAlchemy as BaseSQLAlchemy

from contextlib import contextmanager


# 自定义一个SQLAlchemy继承flask_sqlalchemy的,方便自定义方法
class SQLAlchemy(BaseSQLAlchemy):

	# 利用contextmanager管理器,对try/except语句封装，使用的时候必须和with结合
	@contextmanager
	def auto_commit_db(self):
		try:
			yield  # yield 之前的为enter  之后的为exit
			self.session.commit()
		except Exception as e:
			# 加入数据库commit提交失败，必须回滚
			self.session.rollback()
			print(e)


db = SQLAlchemy()

market_manage_system/models/crud.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   crud.py

@Time    :   2020/12/31 19:37

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from .base import db

def insert(model):
	with db.auto_commit_db():
		db.session.add(model)
	# try:
	# 	db.session.commit()
	# except Exception as e:
	# 	print(e)
	# 	db.session.rollback()
	# 	return 0
	# return 1

def delete(model):
	with db.auto_commit_db():
		db.session.delete(model)

'''
ID:用于搜索要修改的字段【primary key】
**params: 要修改的字段 格式为字典{字段名：新字段值}
'''
def update(model, ID, **params):
	new = model.query.get(ID)
	# 遍历出入的参数，并更新对应值
	for key, value in params.items():
		if value:
			setattr(new, key, value)
	with db.auto_commit_db():
		db.session.add(new)
		# 便于判断是否更新成功
		return new
'''
model 对象序列化
return [{},]
'''
def serialize_dict(model):
	dicts=[]
	for m in model:
		m=m.todict()
		dicts.append(m)
	return dicts

market_manage_system/models/entry_info.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   entry_info.py

@Time    :   2021/1/3 13:15

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from .base import db
from .good_info import Goods
class Entry(db.Model):
	ID = db.Column(db.String(255), primary_key=True)
	goods_ID = db.Column(db.String(255), db.ForeignKey('goods.ID'))
	number = db.Column(db.INTEGER)
	time = db.Column(db.DATE)
	state = db.Column(db.SMALLINT)
	total_amount=db.Column(db.INTEGER)
	goods = db.relationship('Goods', backref='entry')
	def __init__(self,ID,goods_ID,number,time,state,total_amount):
		self.ID=ID
		self.goods_ID=goods_ID
		self.number=number
		self.time=time
		self.state=state
		self.total_amount=total_amount
	def __repr__(self):
		return '<entry_ID %r>' % self.ID
	def todict(self):
		return {
			'ID': self.ID,
			'goods_ID': self.goods_ID,
			'number': self.number,
			'time': self.time,
			'state': self.state,
			'total_amount': self.total_amount
		}

market_manage_system/models/factory_info.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   factory_info.py

@Time    :   2021/1/3 13:10

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from .base import db
class Factory(db.Model):
	ID=db.Column(db.String(255),primary_key=True)
	name=db.Column(db.String(255))
	address=db.Column(db.String(255))
	telephone=db.Column(db.String(255))
	def __init__(self,ID,name,address,telephone):
		self.ID=ID
		self.name=name
		self.address=address
		self.telephone=telephone
	def __repr__(self):
		return '<factory_name %r>' % self.name
	def todict(self):
		return {
			'ID':self.ID,
			'name':self.name,
			'address':self.address,
			'telephone':self.telephone
		}

market_manage_system/models/good_info.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   good_info.py

@Time    :   2021/1/2 20:35

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from .base import db
from .factory_info import Factory
from .supplier_info import Supplier
class Goods(db.Model):
	ID=db.Column(db.String(255),primary_key=True)
	name=db.Column(db.String(255))
	price=db.Column(db.String(255))
	bar_code=db.Column(db.String(255))
	inventory=db.Column(db.INTEGER)
	promotion_price=db.Column(db.String(255))
	start_time=db.Column(db.DATETIME)
	end_time=db.Column(db.DATETIME)
	state=db.Column(db.SMALLINT)
	limit_num=db.Column(db.INTEGER)
	factory_ID=db.Column(db.String(255),db.ForeignKey('factory.ID'))
	supplier_ID=db.Column(db.String(255),db.ForeignKey('supplier.ID'))
	factory=db.relationship('Factory',backref='goods')
	supplier=db.relationship('Supplier',backref='goods')
	def __init__(self,ID,name,price,bar_code,inventory=None,promotion_price=None,start_time=None,end_time=None,state=None,limit_num=None,factory_ID=None,supplier_ID=None):
		self.ID=ID
		self.name=name
		self.price=price
		self.bar_code=bar_code
		self.inventory=inventory
		self.promotion_price=promotion_price
		self.start_time=start_time
		self.end_time=end_time
		self.state=state
		self.limit_num=limit_num
		self.factory_ID=factory_ID
		self.supplier_ID=supplier_ID
	def __repr__(self):
		return '<goods_name %r>' % self.name
	def todict(self):
		return {
			'ID':self.ID,
			'name':self.name,
			'price':self.price,
			'bar_code':self.bar_code,
			'inventory':self.inventory,
			'promotion_price':self.promotion_price,
			'start_time':self.start_time,
			'end_time':self.end_time,
			'state':self.state,
			'limit_num':self.limit_num,
			'factory_ID':self.factory_ID,
			'supplier_ID':self.supplier_ID
		}

market_manage_system/models/member_info.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   member_info.py

@Time    :   2021/1/3 13:08

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from .base import db
class Member(db.Model):
	ID=db.Column(db.String(255),primary_key=True)
	card_ID=db.Column(db.String(255))
	phone_number=db.Column(db.String(255))
	register_date=db.Column(db.DATE)
	renewal_date=db.Column(db.DATE)
	aggregate_amount=db.Column(db.String(255))
	def __init__(self,ID,card_ID,phone_number,register_date,renewal_date,aggregate_amount):
		self.ID=ID
		self.card_ID=card_ID
		self.phone_number=phone_number
		self.register_date=register_date
		self.renewal_date=renewal_date
		self.aggregate_amount=aggregate_amount
	def __repr__(self):
		return '<member_ID %r>' % self.ID

market_manage_system/Forms/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   __init__.py.py

@Time    :   2021/1/4 11:15

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

if __name__ == '__main__':
	pass

market_manage_system/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   __init__.py

@Time    :   2020/12/30 9:53

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''
from flask import Flask
from .  import views
from .  import models
def create_app():
	'''
	instance_relative_config=true  当设置为True时，from_pyfile会从instance_path指定的地址下查找文件
	instsnce_path：不设置，自动寻找与本文件同目录下的instance文件夹
	'''
	app = Flask(__name__, instance_relative_config=True)
	# 寻找instance目录下的文件，此处为config.py
	app.config.from_pyfile('config.py')
	# 添加 jinja 循环控制扩展 使得支持 break 和 continue
	app.jinja_env.add_extension('jinja2.ext.loopcontrols')
	models.init_app(app)
	views.init_app(app)
	return app

market_manage_system/services/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   __init__.py.py

@Time    :   2021/1/5 12:52

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

if __name__ == '__main__':
	pass

market_manage_system/views/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   __init__.py.py

@Time    :   2020/12/30 9:55

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''
from .mains import mains_bp
from .auth import auth_bp
from .purchase import purchase_bp
from .trading import trading_bp
from .goods import goods_bp
from .sales import sales_bp
from .manage import manage_bp
from .inventorys import inventory_bp
def init_app(app):
	app.register_blueprint(mains_bp)
	app.register_blueprint(auth_bp)
	app.register_blueprint(purchase_bp)
	app.register_blueprint(trading_bp)
	app.register_blueprint(goods_bp)
	app.register_blueprint(sales_bp)
	app.register_blueprint(manage_bp)
	app.register_blueprint(inventory_bp)

market_manage_system/views/auth.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   auth.py

@Time    :   2020/12/30 20:30

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''
from  flask import  Blueprint,request,redirect,url_for,render_template,flash,session,g
from werkzeug.security import check_password_hash,generate_password_hash
import  functools
from ..models.auth_info import  Account
from ..models.crud import insert,update,delete
auth_bp=Blueprint('auth',__name__)

@auth_bp.route('/register', methods=('GET', 'POST'))
def register():
	if request.method == 'POST':
		username = request.form['username']
		password = request.form['password']
		info = None
		# 前端判别就行
		# if not username:
		# 	error = 'Username is required.'
		# elif not password:
		# 	error = 'Password is required.'
		account=Account.query.filter_by(username=username).first()
		if account:
			print('User {} is already registered.'.format(username))
			info = 'User {} is already registered.'.format(username)
		else:
			account=Account(username,password)
			insert(account)
			return redirect(url_for('auth.login'))
		flash(info,'warning')
	return render_template('register.html')

@auth_bp.route('/login',methods=('GET', 'POST'))
def login():
	if request.method == 'POST':
		username = request.form['username']
		password = request.form['password']
		info = None
		account = Account.query.filter_by(username=username).first()
		if not account:
			print('Incorrect username.')
			info = 'Incorrect username.'
		elif not check_password_hash(account.password, password):
			info = 'Incorrect password.'
		else:
			session.clear()
			session['account_ID'] = account.ID
			if account.authority :
				return redirect(url_for('manage.manage_people'))
			else:
				return redirect(url_for('goods.goods_enter'))
		flash(info,'warning')
	return render_template('login.html')
'''
before_app_request 注册一个 在视图函数之前运行的函数，不论其 URL 是什么。
load_logged_in_user 检查用户 id 是否已经储存在 session 中，
并从数据库中获取用户数据，然后储存在 g.user 中。 g.user 的持续时间比请求要长。
如果没有用户 id ，或者 id 不存在，那么 g.user 将会是 None 。
'''
@auth_bp.before_app_request
def load_logged_in_user():
	account_ID = session.get('account_ID')
	if account_ID is None:
		g.account = None
	else:
		g.account = Account.query.get(account_ID)

@auth_bp.route('/logout')
def logout():
	session.clear()
	return redirect(url_for('mains.welcome'))

'''
构建一个装饰器，装饰器返回一个新的视图，
该视图包含了传递给装饰器的原视图。新的函数检查用户 是否已载入。
如果已载入，那么就继续正常执行原视图，否则就重定向到登录页面。
'''
def login_required(view):
	@functools.wraps(view)
	def wrapped_view(**kwargs):
		if g.account is None:
			return redirect(url_for('auth.login'))
		return view(**kwargs)
	return wrapped_view

def forbidden_page(view):
	@functools.wraps(view)
	def wrapped_view(**kwargs):
		if g.account.authority is 0:
			return render_template('403.html')
		return view(**kwargs)

	return wrapped_view

market_manage_system/views/goods.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   goods.py

@Time    :   2020/12/30 20:57

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''
from  flask import  Blueprint,request,redirect,url_for,render_template,flash,session,g
from ..Forms.cashier_forms import cashier_add_form,member_form,cashier_cal_form
from ..models.crud import insert,update,delete,serialize_dict
from ..models.good_info import Goods
from ..models.member_info import Member
from ..models.trade_info import Trade
from ..models.sale_info import Sale
from .auth import login_required
import datetime
import random
import string
import time
goods_bp=Blueprint('goods',__name__)
# 定义全局变量
trade_info={'good_list':[],'sum':0.0}
discount=1
serial_num = 0
money_return = 0
member_ID=0
card_ID=0
money_get=0
sale_list=[]
def global_var_init():
	global trade_info, discount, money_return, serial_num, member_ID, card_ID, money_get,sale_list
	trade_info = {'good_list': [], 'sum': 0.0}
	discount = 1
	serial_num = 0
	money_return = 0
	member_ID = 0
	card_ID = 0
	money_get = 0
	sale_list = []
@goods_bp.route('/goods_enter',methods=('GET', 'POST'))
@login_required
def goods_enter():
	if request.method == 'POST':
		ID = request.form['ID']
		name= request.form['name']
		price = request.form['price']
		bar_code = request.form['bar_code']
		# print(ID,name,price,bar_code)
		good=Goods(ID,name,price,bar_code)
		insert(good)
	goods_info=Goods.query.all()
	goods_info=serialize_dict(goods_info)
	# for i in goods_info:
	# 	for key,value in i.items():
	# 		print(key,value)
	# 如果传参必须指定，否则会报错，传参名即为模板里需要的参数名称
	return render_template('goods_enter.html', goods_info=goods_info)
# 后续移动到trade
@goods_bp.route('/cashier',methods=('GET', 'POST'))
@login_required
def cashier():
	global trade_info,discount,money_return,serial_num,member_ID,card_ID,money_get,sale_list
	add_form=cashier_add_form()
	mem_form=member_form()
	cal_form=cashier_cal_form()
	if mem_form.submit.data and mem_form.validate():
		card_ID=mem_form.card_ID.data
		member=Member.query.filter_by(card_ID=card_ID).first()
		if member:
			member_ID =member.ID
			discount=0.95
			print(discount)
			# 给js alter 显示时间
			time.sleep(0.7)
	if add_form.submit.data and add_form.validate():
		name_or_code=add_form.name_or_code.data
		print(name_or_code)
		# 哪个有结果用那个
		good=Goods.query.filter_by(name=name_or_code).first() or Goods.query.filter_by(bar_code=name_or_code).first()
		print(good)
		good_dict=good.todict()
		good_dict['bar_code']=add_form.num.data
		good_dict['inventory']=float(good.price)*float(discount)*float(add_form.num.data)
		trade_info['good_list'].append(good_dict)
		current_price=float(good.price)*float(discount)    # 后期补上是否促销的判断
		trade_info['sum']+=current_price*float(add_form.num.data)
		print(trade_info)
		sale={'ID':''.join(random.sample(string.ascii_letters + string.digits, 10)),
		       'good_ID':good.ID,
		       'num':add_form.num.data,
		       'total_amount':current_price*float(add_form.num.data),
		       'date':datetime.datetime.now().date()}
		sale_list.append(sale)
	if cal_form.submit.data and cal_form.validate():
		money_get=cal_form.money_get.data
		money_return=float(money_get)-trade_info['sum']
		serial_num=''.join(random.sample(string.ascii_letters + string.digits, 10))
		trade=Trade(serial_num,trade_info['sum'],datetime.datetime.now().date(),member_ID,g.account)
		insert(trade)
		for sale in sale_list:
			sale_=Sale(sale['ID'],sale['good_ID'],sale['num'],sale['total_amount'],sale['date'])
			insert(sale_)
		# 给js alter 显示时间
		time.sleep(0.7)
	return render_template('cashier.html',
	                       add_form=add_form,
	                       mem_form=mem_form,
	                       cal_form=cal_form,
	                       trade_info=trade_info,
	                       card_ID=card_ID
	                       )
@goods_bp.route('/trade_print',methods=('GET', 'POST'))
@login_required
def trade_print():
	current_time=datetime.datetime.now().date()
	trade_info_=trade_info
	current_time_=current_time
	money_get_=money_get
	money_return_=money_return
	serial_num_=serial_num
	member_ID_=member_ID
	card_ID_=card_ID
	global_var_init()
	return render_template('trade_print.html',
	                       trade_info=trade_info_,
	                       current_time=current_time_,
	                       money_get=money_get_,
	                       money_return=money_return_,
	                       serial_num=serial_num_,
	                       member_ID=member_ID_,
	                       card_ID=card_ID_
	                       )

market_manage_system/views/inventorys.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

'''
@File    :   inventorys.py

@Time    :   2021/1/5 16:24

@Author  :   Waking

@Contact :   ylzhangcs@hotmail.com
'''

from  flask import  Blueprint,request,render_template,redirect,url_for
from ..models.crud import insert,update,delete,serialize_dict
from ..models.good_info import Goods
from .auth import login_required,forbidden_page
inventory_bp=Blueprint('inventory',__name__)
@inventory_bp.route('/inventory_manage',methods=('GET', 'POST'))
@login_required
@forbidden_page
def inventory_manage():
	if request.method == 'POST':
		ID = request.form['ID']
		name = request.form['name']
		inventory = request.form['inventory']
		operation = request.form['operation']
		if operation == 'update':
			update(Goods, ID, name=name, inventory=inventory)
		else:
			goods = Goods.query.get(ID)
			delete(goods)
	goods=Goods.query.all()
	goods_info=serialize_dict(goods)
	return  render_template('inventory.html',goods_info=goods_info)

market_manage_system/templates/base.html
<!DOCTYPE html>
{% for message in get_flashed_messages(with_categories=True) %}
<div class="alert alert-{{ message[0] }}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message[1] }}
</div>
{% endfor %}
{% block content %}{% endblock %}

market_manage_system/templates/login.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% block content %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>超市管理系统 | 登录</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{{ url_for('auth.login') }}">Market Manage System</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form  action="{{ url_for('auth.login') }}" method="post">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Username" name="username" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-4">

              <a href="{{ url_for('auth.register') }}" class="text-center">
                  <button type="button" class="btn btn-primary btn-block">注 册</button>
              </a>

          </div>
               <div class="col-4">
                <!-- 间隔 -->
            </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">登 录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <!-- /.social-auth-links -->

      <!--<p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>-->

    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='dist/js/adminlte.min.js') }}"></script>

</body>
</html>
{% endblock %}

market_manage_system/templates/register.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% block content %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>超市管理系统 | 注册</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ url_for('static', filename='plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="{{ url_for('auth.register') }}">Market Manage System</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form  action="{{ url_for('auth.register') }}" method="post">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Username" name="username" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" id="first" class="form-control" placeholder="Password" name="password" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" id="second" class="form-control" placeholder="Retype password" required="required" onkeyup="KeyUp()">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>

        </div>
        <div class="row">

            <div class="col-4">
              <a href="{{ url_for('auth.login') }}" >
                  <button type="button" class="btn btn-primary btn-block">登 录 </button>
              </a>
            </div>
            <div class="col-4">
                <!-- 间隔 -->
            </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" id="submit" class="btn btn-primary btn-block">注 册</button>
          </div>
          <!-- /.col -->
        </div>
      </form>




    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='dist/js/adminlte.min.js') }}"></script>
</body>
</html>
    <script>
var commonUtil = {
    /**
     * 弹出消息框
     * @param msg 消息内容
     * @param type 消息框类型（参考bootstrap的alert）
     */
    alert: function (msg, type) {
        if (typeof (type) == "undefined") { // 未传入type则默认为success类型的消息框
            type = "success";
        }
        // 创建bootstrap的alert元素
        var divElement = $("<div></div>").addClass('alert').addClass('alert-' + type).addClass('alert-dismissible');
        divElement.css({ // 消息框的定位样式
            "position": "absolute",
            "top": "80px"
        });
        divElement.text(msg); // 设置消息框的内容
        // 消息框添加可以关闭按钮
        var closeBtn = $('<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>');
        $(divElement).append(closeBtn);
        // 消息框放入到页面中
        $('body').append(divElement);
        return divElement;
    }
}
     var divElement;//声明为全局变量
    function KeyUp() {
            var a = $('#first').val();
            //alert(a);
            var b = $('#second').val();
            //alert(b);

            if (a == b) {
                $('#submit').removeAttr('disabled');
                if (divElement)
                    divElement.remove() //jquery 语法
                    //移除指向的元素后，将变量还原，否则变量仍不为空,仍指向对应jquery dom 元素
                    divElement=undefined
            }
            else {
                $('#submit').attr('disabled', 'disabled');
                if (!divElement)
                    //只有变量为undefined 时候才生成，避免重复生成
                divElement=commonUtil.alert('两次密码不一致','warning')

            }
            /*
            该方法会重复生成 多个 提示框，
            而全局变量 diveElement所指向的元素永远是最新的（每次新的提示框覆盖上一次的提示框）
            导致最后只能删除最新的提示框，旧的则无法删除
                 if (a == b) {
                $('#submit').removeAttr('disabled');
                if (divElement)
                    divElement.remove()
            }
            else {
                $('#submit').attr('disabled', 'disabled');
                divElement=commonUtil.alert('两次密码不一致','warning')

            }
             */
        }
        </script>
{% endblock %}